In [1]:
import sys
import pandas as pd
 
print("Python is working!")
print("pandas version:", pd.__version__)


Python is working!
pandas version: 2.3.3


In [1]:
customer = "Avlin"
bill_amount = 1250

print(f"Receipt: {customer} paid ₹{bill_amount}")

Receipt: Avlin paid ₹1250


In [2]:
sales = [1200, 980, 1500, 1100, 1750]

print("Total:", sum(sales))
print("Biggest value:", max(sales))

Total: 6530
Biggest value: 1750


In [3]:
quantity = 15

if quantity >= 20:
    print("Discount: 20%")
elif quantity >= 10:
    print("Discount: 10%")
else:
    print("No discount")

Discount: 10%


In [4]:
prices = {
    "apple": 50,
    "banana": 20,
    "orange": 30
}

basket = ["apple", "banana", "orange"]

total = 0

for item in basket:
    total += prices[item]

print("Basket total:", total)

Basket total: 100


In [5]:
def final_price(price, percent):
    discount = price * percent / 100
    return price - discount

print(final_price(1000, 10))
print(final_price(500, 20))

900.0
400.0


In [7]:
sales = [
    {"fruit": "apple",  "qty": 12, "price": 30},
    {"fruit": "orange", "qty": 7,  "price": 20},
    {"fruit": "banana", "qty": 20, "price": 10},
    {"fruit": "apple",  "qty": 5,  "price": 30},
    {"fruit": "mango",  "qty": 3,  "price": 40},
]

stock_left = {"apple": 4, "orange": 15, "banana": 2, "mango": 9}
reorder_level = 5

In [8]:
sold = {}

for sale in sales:
    fruit = sale["fruit"]
    qty = sale["qty"]

    if fruit in sold:
        sold[fruit] += qty
    else:
        sold[fruit] = qty

print(sold)

{'apple': 17, 'orange': 7, 'banana': 20, 'mango': 3}


In [9]:
best_seller = max(sold, key=sold.get)
print("Best seller:", best_seller)

Best seller: banana


In [10]:
reorder = []

for fruit, stock in stock_left.items():
    if stock <= reorder_level:
        reorder.append(fruit)

print("Reorder now:", reorder)

Reorder now: ['apple', 'banana']


In [12]:
total_revenue = 0

for sale in sales:
    total_revenue = total_revenue + sale["qty"] * sale["price"]

print("Total revenue:", total_revenue)

Total revenue: 970


In [13]:
def day_summary():
    print("Total revenue: ₹", total_revenue)
    print("Sold per fruit:", sold)
    print("Best seller:", best_seller)
    print("Reorder now:", reorder)

day_summary()

Total revenue: ₹ 970
Sold per fruit: {'apple': 17, 'orange': 7, 'banana': 20, 'mango': 3}
Best seller: banana
Reorder now: ['apple', 'banana']


In [1]:
## Day 2 - NumPy

In [2]:
import numpy as np


In [3]:
prices = np.array([30, 20, 10, 40])   # apple, orange, banana, mango
print(prices)
print(len(prices))


[30 20 10 40]
4


In [4]:
weights = np.array([2, 1.5, 3, 0.5, 4])
print(weights)

[2.  1.5 3.  0.5 4. ]


In [5]:
import numpy as np
sales = np.array([1200, 980, 1500, 1100, 1750, 1300, 900])
print(sales)

[1200  980 1500 1100 1750 1300  900]


In [6]:
weights = np.array([2, 1.5, 3, 0.5, 4])
print(weights)
print(len(weights))   # number of baskets

[2.  1.5 3.  0.5 4. ]
5


In [7]:
prices = np.array([30, 20, 10, 40])
new_prices = prices * 1.10  
print(new_prices)
print(prices + 5)               


[33. 22. 11. 44.]
[35 25 15 45]


In [9]:
qty = np.array([17, 7, 20, 3])
prices = np.array([30, 20, 10, 40])
revenue = qty * prices  
print(revenue)


[510 140 200 120]


In [10]:
prices = np.array([30, 20, 10, 40])   
weights = np.array([2, 1.5, 3, 0.5, 4])
print(prices - 5)

[25 15  5 35]


In [12]:
print(weights * 1000)

[2000. 1500. 3000.  500. 4000.]


In [13]:
qty = np.array([17, 7, 20, 3])
prices = np.array([30, 20, 10, 40])
revenue = qty * prices         
print(revenue)


[510 140 200 120]


In [14]:
week = np.array([1200, 980, 1500, 1100, 1750, 1300, 900])

In [15]:
print(week.sum())

8730


In [16]:
print(week.max())

1750


In [17]:
print(week.min())

900


In [18]:
print(week.mean())

1247.142857142857


In [19]:
print(week[2])

1500


In [20]:
print(week[0:5])

[1200  980 1500 1100 1750]


In [21]:
print(week[-2:])

[1300  900]


In [22]:
print(week.sum())

8730


In [23]:
print(round(week.mean()))

1247


In [25]:
bestdaysale= week.max()
print("best days's sale:",bestdaysale)

best days's sale: 1750


In [26]:
x=week.min()
print("Worst days sale:",x)

Worst days sale: 900


In [3]:
import numpy as np
week = np.array([1200, 980, 1500, 1100, 1750, 1300, 900])
print(week > 1200)  
print(week[week > 1200])      
print((week > 1200).sum())    


[False False  True False  True  True False]
[1500 1750 1300]
3


In [4]:
import numpy as np

week = np.array([1200, 980, 1500, 1100, 1750, 1300, 900])

In [6]:
print(week>week.mean())

[False False  True False  True  True False]


In [7]:
print(week[week>1200])

[1500 1750 1300]


In [10]:
print((week<1000).sum())

2


In [11]:
q=np.array([[1200,1500,1600],
           [1400,1000,3000],
           [1200,3400,1200]])
print(q.sum(axis=1))
print(q.sum(axis=0))

[4300 5400 5800]
[3800 5900 5800]


In [12]:
fruits = ["apple", "orange", "banana", "mango"]
prices = np.array([30, 20, 10, 40])
 
# rows = fruits, columns = Mon..Sun (7 days)
q = np.array([[12,  5,  8, 10, 14,  9,  6],   # apple
              [ 7, 10,  6,  8,  5, 11,  4],   # orange
              [20, 15, 18, 22, 25, 19, 12],   # banana
              [ 3,  4,  2,  5,  6,  3,  1]])  # mango


In [13]:
print(q.sum(axis=1))

[ 64  51 131  24]


In [14]:
qty=(q.sum(axis=1))
print(qty)

[ 64  51 131  24]


In [15]:
totalrevenue=qty*prices
print(totalrevenue)

[1920 1020 1310  960]


In [17]:
total=(totalrevenue.sum())
print(total)

5210


In [18]:
qtyperday=(q.sum(axis=0))
print(qtyperday)

[42 34 34 45 50 42 23]


In [19]:
print(qtyperday>40)

[ True False False  True  True  True False]


In [26]:
daysabove40=qtyperday[qtyperday>40]
print(daysabove40)

[42 45 50 42]


In [23]:
count=(qtyperday>40).sum()
print(count)

4


In [27]:
print("Week in review")
print("total quantity per week:",qty)
print("revenue per fruit:",totalrevenue)
print("Total weekly revenue:",total)
print("total quantity sold per day:",qtyperday)
print("days sold above 40 fruits:",daysabove40)
print("no of days sold above 40 fruits:",count)

Week in review
total quantity per week: [ 64  51 131  24]
revenue per fruit: [1920 1020 1310  960]
Total weekly revenue: 5210
total quantity sold per day: [42 34 34 45 50 42 23]
days sold above 40 fruits: [42 45 50 42]
no of days sold above 40 fruits: 4


In [28]:
import numpy as np

days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]

prices = np.array([30, 20, 10, 40])

q = np.array([[12,  5,  8, 10, 14,  9,  6],
              [ 7, 10,  6,  8,  5, 11,  4],
              [20, 15, 18, 22, 25, 19, 12],
              [ 3,  4,  2,  5,  6,  3,  1]])

daily_totals = q.sum(axis=0)

In [29]:
bestday = np.argmax(daily_totals)
print(days[bestday])

Fri


In [31]:
percentages = (daily_totals / daily_totals.sum() * 100).round(1)

In [32]:
print(percentages)

[15.6 12.6 12.6 16.7 18.5 15.6  8.5]


In [34]:
print(q.max())

25


In [35]:
row, col = np.unravel_index(np.argmax(q), q.shape)

fruits = ["apple", "orange", "banana", "mango"]

print("Fruit:", fruits[row])
print("Day:", days[col])
print("Quantity:", q[row, col])

Fruit: banana
Day: Fri
Quantity: 25
