In [31]:
import numpy as np


In [32]:
prices = np.array([30, 20, 10, 40])   # apple, orange, banana, mango
print(prices)
print(len(prices))


[30 20 10 40]
4


In [33]:
weights = np.array([2, 1.5, 3, 0.5, 4])
print(weights)

[2.  1.5 3.  0.5 4. ]


In [34]:
import numpy as np
sales = np.array([1200, 980, 1500, 1100, 1750, 1300, 900])
print(sales)

[1200  980 1500 1100 1750 1300  900]


In [35]:
weights = np.array([2, 1.5, 3, 0.5, 4])
print(weights)
print(len(weights))   # number of baskets

[2.  1.5 3.  0.5 4. ]
5


In [36]:
prices = np.array([30, 20, 10, 40])
new_prices = prices * 1.10  
print(new_prices)
print(prices + 5)               


[33. 22. 11. 44.]
[35 25 15 45]


In [37]:
qty = np.array([17, 7, 20, 3])
prices = np.array([30, 20, 10, 40])
revenue = qty * prices  
print(revenue)


[510 140 200 120]


In [38]:
prices = np.array([30, 20, 10, 40])   
weights = np.array([2, 1.5, 3, 0.5, 4])
print(prices - 5)

[25 15  5 35]


In [39]:
print(weights * 1000)

[2000. 1500. 3000.  500. 4000.]


In [42]:
qty = np.array([17, 7, 20, 3])
prices = np.array([30, 20, 10, 40])
revenue = qty * prices        
print(revenue)


[510 140 200 120]


In [43]:
week = np.array([1200, 980, 1500, 1100, 1750, 1300, 900])

In [44]:
print(week.sum())

8730


In [45]:
print(week.max())

1750


In [46]:
print(week.min())

900


In [47]:
print(week.mean())

1247.142857142857


In [48]:
print(week[2])

1500


In [49]:
print(week[0:5])

[1200  980 1500 1100 1750]


In [50]:
print(week[-2:])

[1300  900]


In [51]:
print(week.sum())

8730


In [52]:
print(round(week.mean()))

1247


In [53]:
bestdaysale= week.max()
print("best days's sale:",bestdaysale)

best days's sale: 1750


In [55]:
x=week.min()
print("Worst days sale:",x)

Worst days sale: 900


In [56]:
import numpy as np
week = np.array([1200, 980, 1500, 1100, 1750, 1300, 900])
print(week > 1200)  
print(week[week > 1200])      
print((week > 1200).sum())    


[False False  True False  True  True False]
[1500 1750 1300]
3


In [57]:
import numpy as np

week = np.array([1200, 980, 1500, 1100, 1750, 1300, 900])

In [58]:
print(week>week.mean())

[False False  True False  True  True False]


In [59]:
print(week[week>1200])

[1500 1750 1300]


In [60]:
print((week<1000).sum())

2


In [61]:
q=np.array([[1200,1500,1600],
           [1400,1000,3000],
           [1200,3400,1200]])
print(q.sum(axis=1))
print(q.sum(axis=0))

[4300 5400 5800]
[3800 5900 5800]


In [62]:
fruits = ["apple", "orange", "banana", "mango"]
prices = np.array([30, 20, 10, 40])
 
# rows = fruits, columns = Mon..Sun (7 days)
q = np.array([[12,  5,  8, 10, 14,  9,  6],   # apple
              [ 7, 10,  6,  8,  5, 11,  4],   # orange
              [20, 15, 18, 22, 25, 19, 12],   # banana
              [ 3,  4,  2,  5,  6,  3,  1]])  # mango


In [63]:
print(q.sum(axis=1))

[ 64  51 131  24]


In [64]:
qty=(q.sum(axis=1))
print(qty)

[ 64  51 131  24]


In [65]:
totalrevenue=qty*prices
print(totalrevenue)

[1920 1020 1310  960]


In [66]:
total=(totalrevenue.sum())
print(total)

5210


In [67]:
qtyperday=(q.sum(axis=0))
print(qtyperday)

[42 34 34 45 50 42 23]


In [68]:
print(qtyperday>40)

[ True False False  True  True  True False]


In [69]:
daysabove40=qtyperday[qtyperday>40]
print(daysabove40)

[42 45 50 42]


In [70]:
count=(qtyperday>40).sum()
print(count)

4


In [71]:
print("Week in review")
print("total quantity per week:",qty)
print("revenue per fruit:",totalrevenue)
print("Total weekly revenue:",total)
print("total quantity sold per day:",qtyperday)
print("days sold above 40 fruits:",daysabove40)
print("no of days sold above 40 fruits:",count)

Week in review
total quantity per week: [ 64  51 131  24]
revenue per fruit: [1920 1020 1310  960]
Total weekly revenue: 5210
total quantity sold per day: [42 34 34 45 50 42 23]
days sold above 40 fruits: [42 45 50 42]
no of days sold above 40 fruits: 4


In [72]:
import numpy as np

days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]

prices = np.array([30, 20, 10, 40])

q = np.array([[12,  5,  8, 10, 14,  9,  6],
              [ 7, 10,  6,  8,  5, 11,  4],
              [20, 15, 18, 22, 25, 19, 12],
              [ 3,  4,  2,  5,  6,  3,  1]])

daily_totals = q.sum(axis=0)

In [74]:
bestday = np.argmax(daily_totals)
print(days[bestday])

Fri


In [75]:
print(percentages)

NameError: name 'percentages' is not defined

In [76]:
print(q.max())

25


In [77]:
row, col = np.unravel_index(np.argmax(q), q.shape)

fruits = ["apple", "orange", "banana", "mango"]

print("Fruit:", fruits[row])
print("Day:", days[col])
print("Quantity:", q[row, col])

Fruit: banana
Day: Fri
Quantity: 25
